<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220228164936 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('DROP SEQUENCE bl_vat_id_seq CASCADE');
        $this->addSql('CREATE TABLE new_api_user (id SERIAL NOT NULL, code VARCHAR(225) NOT NULL, role VARCHAR(225) NOT NULL, mail VARCHAR(225) NOT NULL, username VARCHAR(225) NOT NULL, password VARCHAR(255) NOT NULL, roles VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE token_api_user (id SERIAL NOT NULL, name VARCHAR(50) NOT NULL, token VARCHAR(180) NOT NULL, roles JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D83B7D395F37A13B ON token_api_user (token)');
        $this->addSql('ALTER TABLE back_group ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE back_group ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_group ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE back_group ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_group ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE back_user DROP CONSTRAINT fk_back_user_group');
        $this->addSql('ALTER TABLE back_user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE back_user ALTER group_id DROP NOT NULL');
        $this->addSql('ALTER TABLE back_user ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_user ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE back_user ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_user ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE back_user ADD CONSTRAINT FK_4624E507FE54D947 FOREIGN KEY (group_id) REFERENCES back_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_client DROP CONSTRAINT fk_bl_client_company');
        $this->addSql('ALTER TABLE bl_client DROP CONSTRAINT fk_bl_client_country');
        $this->addSql('ALTER TABLE bl_client DROP CONSTRAINT fk_bl_client_payment_condition');
        $this->addSql('ALTER TABLE bl_client ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_client ALTER country_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_client ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_client ALTER payment_condition_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_client ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_client ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_client ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_client ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_client ADD CONSTRAINT FK_B0C334D0979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_client ADD CONSTRAINT FK_B0C334D0F92F3E70 FOREIGN KEY (country_id) REFERENCES bl_country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_client ADD CONSTRAINT FK_B0C334D0EE8724AC FOREIGN KEY (payment_condition_id) REFERENCES bl_payment_condition (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_company DROP CONSTRAINT fk_bl_company_country');
        $this->addSql('ALTER TABLE bl_company ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_company ALTER country_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_company ALTER vat_exempt DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_company ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_company ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_company ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_company ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_company ALTER complete DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_company ADD CONSTRAINT FK_D21AF9D0F92F3E70 FOREIGN KEY (country_id) REFERENCES bl_country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_country DROP CONSTRAINT fk_country_currency');
        $this->addSql('ALTER TABLE bl_country ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_country ALTER currency_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_country ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_country ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_country ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_country ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_country ADD CONSTRAINT FK_CED639F938248176 FOREIGN KEY (currency_id) REFERENCES bl_currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_currency ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_currency ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_currency ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_currency ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_currency ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_iban DROP CONSTRAINT fk_bl_iban_company');
        $this->addSql('ALTER TABLE bl_iban ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_iban ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_iban ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_iban ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_iban ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_iban ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_iban ALTER is_default DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_iban ADD CONSTRAINT FK_9FA1A4F7979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_language ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_language ALTER code TYPE VARCHAR(2)');
        $this->addSql('ALTER TABLE bl_language ALTER code DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_language ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_language ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_language ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_language ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_payment_condition DROP CONSTRAINT fk_bl_payment_condition_company');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER value DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER is_default DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_payment_condition ADD CONSTRAINT FK_341B4981979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT fk_bl_product_company');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT fk_bl_product_unit');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT fk_bl_product_vat');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT fk_bl_product_unity');
        $this->addSql('ALTER TABLE bl_product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_product ALTER vat_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_product ALTER unity_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_product ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_product ALTER unit_price TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE bl_product ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_product ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_product ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_product ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT FK_4EEFF432979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT FK_4EEFF432F6859C8C FOREIGN KEY (unity_id) REFERENCES bl_unity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT FK_4EEFF432B5B63A6B FOREIGN KEY (vat_id) REFERENCES bl_vat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_4eeff432f6859c8c RENAME TO IDX_4EEFF432F8BD700D');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT fk_bl_estimate_company');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT fk_bl_estimate_creator');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT fk_bl_estimate_updator');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT fk_bl_estimate_client');
        $this->addSql('ALTER TABLE bl_quote ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote ALTER creator_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote ALTER client_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote ALTER date_begin TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER date_begin SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_quote ALTER date_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER date_end DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote ALTER discount TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE bl_quote ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_quote ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT FK_EB71D8F5979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT FK_EB71D8F561220EA6 FOREIGN KEY (creator_id) REFERENCES bl_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT FK_EB71D8F5A9CED711 FOREIGN KEY (updator_id) REFERENCES bl_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT FK_EB71D8F519EB6921 FOREIGN KEY (client_id) REFERENCES bl_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_config DROP CONSTRAINT fk_quote_config_currency');
        $this->addSql('ALTER TABLE bl_quote_config DROP CONSTRAINT fk_quote_config_language');
        $this->addSql('ALTER TABLE bl_quote_config DROP CONSTRAINT fk_quote_config_quote');
        $this->addSql('ALTER TABLE bl_quote_config ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_config ALTER quote_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_config ALTER language_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_config ALTER currency_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_config ALTER discount DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_config ADD CONSTRAINT FK_205E4C8538248176 FOREIGN KEY (currency_id) REFERENCES bl_currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_config ADD CONSTRAINT FK_205E4C8582F1BAF4 FOREIGN KEY (language_id) REFERENCES bl_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_config ADD CONSTRAINT FK_205E4C85DB805178 FOREIGN KEY (quote_id) REFERENCES bl_quote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_product DROP CONSTRAINT fk_bl_quote_product_unit');
        $this->addSql('ALTER TABLE bl_quote_product DROP CONSTRAINT fk_bl_quote_product_vat');
        $this->addSql('ALTER TABLE bl_quote_product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_product ALTER vat_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_product ALTER unity_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_product ALTER pdate TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote_product ALTER pdate DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_product ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote_product ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_quote_product ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote_product ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_product ADD CONSTRAINT FK_17DF9A76F6859C8C FOREIGN KEY (unity_id) REFERENCES bl_unity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_product ADD CONSTRAINT FK_17DF9A76B5B63A6B FOREIGN KEY (vat_id) REFERENCES bl_vat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_17df9a76f6859c8c RENAME TO IDX_17DF9A76F8BD700D');
        $this->addSql('ALTER TABLE bl_tax DROP CONSTRAINT fk_bl_tax_company');
        $this->addSql('ALTER TABLE bl_tax ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_tax ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_tax ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax ADD CONSTRAINT FK_4A92E92E979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_tax_value DROP CONSTRAINT fk_tax_value');
        $this->addSql('ALTER TABLE bl_tax_value ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax_value ALTER tax_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_begin TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_begin SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_end DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax_value ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_tax_value ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax_value ADD CONSTRAINT FK_E5695479B2A824D8 FOREIGN KEY (tax_id) REFERENCES bl_tax (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_unity DROP CONSTRAINT fk_bl_unit_company');
        $this->addSql('ALTER TABLE bl_unity ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_unity ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_unity ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE bl_unity ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_unity ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_unity ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_unity ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_unity ADD CONSTRAINT FK_89658E56979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_89658e56979b1ad6 RENAME TO IDX_B9CFC6C6979B1AD6');
        $this->addSql('ALTER TABLE bl_user DROP CONSTRAINT bl_user_fkey');
        $this->addSql('ALTER TABLE bl_user DROP CONSTRAINT fk_user_company');
        $this->addSql('ALTER TABLE bl_user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_user ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_user ALTER token DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_user ALTER active DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_user ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_user ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_user ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_user ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_user ALTER enabled DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_user ADD CONSTRAINT FK_E8E71CDCD526A7D3 FOREIGN KEY (parent_user_id) REFERENCES bl_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_user ADD CONSTRAINT FK_E8E71CDC979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_vat DROP CONSTRAINT fk_bl_vat_company');
        $this->addSql('ALTER TABLE bl_vat ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_vat ALTER company_id DROP NOT NULL');
        $this->addSql('ALTER TABLE bl_vat ALTER is_default DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_vat ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_vat ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_vat ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_vat ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_vat ADD CONSTRAINT FK_40A0716B979B1AD6 FOREIGN KEY (company_id) REFERENCES bl_company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wording ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE wording ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording ALTER updated_at DROP DEFAULT');
        $this->addSql('CREATE SEQUENCE wording_domain_id_seq');
        $this->addSql('SELECT setval(\'wording_domain_id_seq\', (SELECT MAX(id) FROM wording_domain))');
        $this->addSql('ALTER TABLE wording_domain ALTER id SET DEFAULT nextval(\'wording_domain_id_seq\')');
        $this->addSql('ALTER TABLE wording_domain ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_domain ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE wording_domain ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_domain ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE wording_translation ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_translation ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE wording_translation ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_translation ALTER updated_at DROP DEFAULT');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SEQUENCE bl_vat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('DROP TABLE new_api_user');
        $this->addSql('DROP TABLE token_api_user');
        $this->addSql('ALTER TABLE bl_unity DROP CONSTRAINT FK_89658E56979B1AD6');
        $this->addSql('CREATE SEQUENCE bl_unity_id_seq');
        $this->addSql('SELECT setval(\'bl_unity_id_seq\', (SELECT MAX(id) FROM bl_unity))');
        $this->addSql('ALTER TABLE bl_unity ALTER id SET DEFAULT nextval(\'bl_unity_id_seq\')');
        $this->addSql('ALTER TABLE bl_unity ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_unity ALTER name TYPE VARCHAR(25)');
        $this->addSql('ALTER TABLE bl_unity ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_unity ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_unity ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_unity ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_unity ADD CONSTRAINT fk_bl_unit_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_b9cfc6c6979b1ad6 RENAME TO IDX_89658E56979B1AD6');
        $this->addSql('ALTER TABLE bl_vat DROP CONSTRAINT FK_40A0716B979B1AD6');
        $this->addSql('CREATE SEQUENCE bl_vat_id_seq');
        $this->addSql('SELECT setval(\'bl_vat_id_seq\', (SELECT MAX(id) FROM bl_vat))');
        $this->addSql('ALTER TABLE bl_vat ALTER id SET DEFAULT nextval(\'bl_vat_id_seq\')');
        $this->addSql('ALTER TABLE bl_vat ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_vat ALTER is_default SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_vat ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_vat ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_vat ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_vat ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_vat ADD CONSTRAINT fk_bl_vat_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_company DROP CONSTRAINT FK_D21AF9D0F92F3E70');
        $this->addSql('CREATE SEQUENCE bl_company_id_seq');
        $this->addSql('SELECT setval(\'bl_company_id_seq\', (SELECT MAX(id) FROM bl_company))');
        $this->addSql('ALTER TABLE bl_company ALTER id SET DEFAULT nextval(\'bl_company_id_seq\')');
        $this->addSql('ALTER TABLE bl_company ALTER country_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_company ALTER vat_exempt SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_company ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_company ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_company ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_company ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_company ALTER complete SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_company ADD CONSTRAINT fk_bl_company_country FOREIGN KEY (country_id) REFERENCES bl_country (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_user DROP CONSTRAINT FK_E8E71CDCD526A7D3');
        $this->addSql('ALTER TABLE bl_user DROP CONSTRAINT FK_E8E71CDC979B1AD6');
        $this->addSql('CREATE SEQUENCE bl_user_id_seq');
        $this->addSql('SELECT setval(\'bl_user_id_seq\', (SELECT MAX(id) FROM bl_user))');
        $this->addSql('ALTER TABLE bl_user ALTER id SET DEFAULT nextval(\'bl_user_id_seq\')');
        $this->addSql('ALTER TABLE bl_user ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_user ALTER token SET NOT NULL');
        $this->addSql('ALTER TABLE bl_user ALTER active SET DEFAULT \'true\'');
        $this->addSql('ALTER TABLE bl_user ALTER enabled SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_user ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_user ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_user ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_user ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_user ADD CONSTRAINT bl_user_fkey FOREIGN KEY (parent_user_id) REFERENCES bl_user (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_user ADD CONSTRAINT fk_user_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE bl_currency_id_seq');
        $this->addSql('SELECT setval(\'bl_currency_id_seq\', (SELECT MAX(id) FROM bl_currency))');
        $this->addSql('ALTER TABLE bl_currency ALTER id SET DEFAULT nextval(\'bl_currency_id_seq\')');
        $this->addSql('ALTER TABLE bl_currency ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_currency ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_currency ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_currency ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_country DROP CONSTRAINT FK_CED639F938248176');
        $this->addSql('CREATE SEQUENCE bl_country_id_seq');
        $this->addSql('SELECT setval(\'bl_country_id_seq\', (SELECT MAX(id) FROM bl_country))');
        $this->addSql('ALTER TABLE bl_country ALTER id SET DEFAULT nextval(\'bl_country_id_seq\')');
        $this->addSql('ALTER TABLE bl_country ALTER currency_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_country ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_country ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_country ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_country ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_country ADD CONSTRAINT fk_country_currency FOREIGN KEY (currency_id) REFERENCES bl_currency (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT FK_4EEFF432979B1AD6');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT FK_4EEFF432F6859C8C');
        $this->addSql('ALTER TABLE bl_product DROP CONSTRAINT FK_4EEFF432B5B63A6B');
        $this->addSql('CREATE SEQUENCE bl_product_id_seq');
        $this->addSql('SELECT setval(\'bl_product_id_seq\', (SELECT MAX(id) FROM bl_product))');
        $this->addSql('ALTER TABLE bl_product ALTER id SET DEFAULT nextval(\'bl_product_id_seq\')');
        $this->addSql('ALTER TABLE bl_product ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_product ALTER unity_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_product ALTER vat_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_product ALTER unit_price TYPE NUMERIC(10, 3)');
        $this->addSql('ALTER TABLE bl_product ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_product ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_product ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_product ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT fk_bl_product_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT fk_bl_product_unit FOREIGN KEY (unity_id) REFERENCES bl_unity (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT fk_bl_product_vat FOREIGN KEY (vat_id) REFERENCES bl_vat (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_product ADD CONSTRAINT fk_bl_product_unity FOREIGN KEY (unity_id) REFERENCES bl_unity (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_4eeff432f8bd700d RENAME TO IDX_4EEFF432F6859C8C');
        $this->addSql('ALTER TABLE bl_quote_config DROP CONSTRAINT FK_205E4C8538248176');
        $this->addSql('ALTER TABLE bl_quote_config DROP CONSTRAINT FK_205E4C8582F1BAF4');
        $this->addSql('ALTER TABLE bl_quote_config DROP CONSTRAINT FK_205E4C85DB805178');
        $this->addSql('CREATE SEQUENCE bl_quote_config_id_seq');
        $this->addSql('SELECT setval(\'bl_quote_config_id_seq\', (SELECT MAX(id) FROM bl_quote_config))');
        $this->addSql('ALTER TABLE bl_quote_config ALTER id SET DEFAULT nextval(\'bl_quote_config_id_seq\')');
        $this->addSql('ALTER TABLE bl_quote_config ALTER currency_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_config ALTER language_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_config ALTER quote_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_config ALTER discount SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_quote_config ADD CONSTRAINT fk_quote_config_currency FOREIGN KEY (currency_id) REFERENCES bl_currency (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_config ADD CONSTRAINT fk_quote_config_language FOREIGN KEY (language_id) REFERENCES bl_language (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_config ADD CONSTRAINT fk_quote_config_quote FOREIGN KEY (quote_id) REFERENCES bl_quote (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT FK_EB71D8F5979B1AD6');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT FK_EB71D8F561220EA6');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT FK_EB71D8F5A9CED711');
        $this->addSql('ALTER TABLE bl_quote DROP CONSTRAINT FK_EB71D8F519EB6921');
        $this->addSql('CREATE SEQUENCE bl_quote_id_seq');
        $this->addSql('SELECT setval(\'bl_quote_id_seq\', (SELECT MAX(id) FROM bl_quote))');
        $this->addSql('ALTER TABLE bl_quote ALTER id SET DEFAULT nextval(\'bl_quote_id_seq\')');
        $this->addSql('ALTER TABLE bl_quote ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote ALTER creator_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote ALTER client_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote ALTER date_begin TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER date_begin SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_quote ALTER date_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER date_end DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote ALTER discount TYPE NUMERIC(10, 3)');
        $this->addSql('ALTER TABLE bl_quote ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_quote ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT fk_bl_estimate_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT fk_bl_estimate_creator FOREIGN KEY (creator_id) REFERENCES bl_user (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT fk_bl_estimate_updator FOREIGN KEY (updator_id) REFERENCES bl_user (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote ADD CONSTRAINT fk_bl_estimate_client FOREIGN KEY (client_id) REFERENCES bl_client (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE bl_language_id_seq');
        $this->addSql('SELECT setval(\'bl_language_id_seq\', (SELECT MAX(id) FROM bl_language))');
        $this->addSql('ALTER TABLE bl_language ALTER id SET DEFAULT nextval(\'bl_language_id_seq\')');
        $this->addSql('ALTER TABLE bl_language ALTER code TYPE UUID');
        $this->addSql('ALTER TABLE bl_language ALTER code SET DEFAULT \'uuid_generate_v4()\'');
        $this->addSql('ALTER TABLE bl_language ALTER code TYPE UUID');
        $this->addSql('ALTER TABLE bl_language ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_language ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_language ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_language ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_iban DROP CONSTRAINT FK_9FA1A4F7979B1AD6');
        $this->addSql('CREATE SEQUENCE bl_iban_id_seq');
        $this->addSql('SELECT setval(\'bl_iban_id_seq\', (SELECT MAX(id) FROM bl_iban))');
        $this->addSql('ALTER TABLE bl_iban ALTER id SET DEFAULT nextval(\'bl_iban_id_seq\')');
        $this->addSql('ALTER TABLE bl_iban ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_iban ALTER is_default SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_iban ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_iban ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_iban ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_iban ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_iban ADD CONSTRAINT fk_bl_iban_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wording_domain ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE wording_domain ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_domain ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE wording_domain ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_domain ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE wording ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE wording ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE wording_translation ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_translation ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE wording_translation ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE wording_translation ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax DROP CONSTRAINT FK_4A92E92E979B1AD6');
        $this->addSql('CREATE SEQUENCE bl_tax_id_seq');
        $this->addSql('SELECT setval(\'bl_tax_id_seq\', (SELECT MAX(id) FROM bl_tax))');
        $this->addSql('ALTER TABLE bl_tax ALTER id SET DEFAULT nextval(\'bl_tax_id_seq\')');
        $this->addSql('ALTER TABLE bl_tax ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_tax ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_tax ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax ADD CONSTRAINT fk_bl_tax_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_payment_condition DROP CONSTRAINT FK_341B4981979B1AD6');
        $this->addSql('CREATE SEQUENCE bl_payment_condition_id_seq');
        $this->addSql('SELECT setval(\'bl_payment_condition_id_seq\', (SELECT MAX(id) FROM bl_payment_condition))');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER id SET DEFAULT nextval(\'bl_payment_condition_id_seq\')');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER value SET DEFAULT 0');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER is_default SET DEFAULT \'false\'');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_payment_condition ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_payment_condition ADD CONSTRAINT fk_bl_payment_condition_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_client DROP CONSTRAINT FK_B0C334D0979B1AD6');
        $this->addSql('ALTER TABLE bl_client DROP CONSTRAINT FK_B0C334D0F92F3E70');
        $this->addSql('ALTER TABLE bl_client DROP CONSTRAINT FK_B0C334D0EE8724AC');
        $this->addSql('CREATE SEQUENCE bl_client_id_seq');
        $this->addSql('SELECT setval(\'bl_client_id_seq\', (SELECT MAX(id) FROM bl_client))');
        $this->addSql('ALTER TABLE bl_client ALTER id SET DEFAULT nextval(\'bl_client_id_seq\')');
        $this->addSql('ALTER TABLE bl_client ALTER company_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_client ALTER country_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_client ALTER payment_condition_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_client ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_client ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_client ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_client ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_client ADD CONSTRAINT fk_bl_client_company FOREIGN KEY (company_id) REFERENCES bl_company (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_client ADD CONSTRAINT fk_bl_client_country FOREIGN KEY (country_id) REFERENCES bl_country (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_client ADD CONSTRAINT fk_bl_client_payment_condition FOREIGN KEY (payment_condition_id) REFERENCES bl_payment_condition (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE SEQUENCE back_group_id_seq');
        $this->addSql('SELECT setval(\'back_group_id_seq\', (SELECT MAX(id) FROM back_group))');
        $this->addSql('ALTER TABLE back_group ALTER id SET DEFAULT nextval(\'back_group_id_seq\')');
        $this->addSql('ALTER TABLE back_group ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_group ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE back_group ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_group ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax_value DROP CONSTRAINT FK_E5695479B2A824D8');
        $this->addSql('CREATE SEQUENCE bl_tax_value_id_seq');
        $this->addSql('SELECT setval(\'bl_tax_value_id_seq\', (SELECT MAX(id) FROM bl_tax_value))');
        $this->addSql('ALTER TABLE bl_tax_value ALTER id SET DEFAULT nextval(\'bl_tax_value_id_seq\')');
        $this->addSql('ALTER TABLE bl_tax_value ALTER tax_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_begin TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_begin SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_end TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER date_end DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax_value ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_tax_value ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_tax_value ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_tax_value ADD CONSTRAINT fk_tax_value FOREIGN KEY (tax_id) REFERENCES bl_tax (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE back_user DROP CONSTRAINT FK_4624E507FE54D947');
        $this->addSql('CREATE SEQUENCE back_user_id_seq');
        $this->addSql('SELECT setval(\'back_user_id_seq\', (SELECT MAX(id) FROM back_user))');
        $this->addSql('ALTER TABLE back_user ALTER id SET DEFAULT nextval(\'back_user_id_seq\')');
        $this->addSql('ALTER TABLE back_user ALTER group_id SET NOT NULL');
        $this->addSql('ALTER TABLE back_user ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_user ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE back_user ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE back_user ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE back_user ADD CONSTRAINT fk_back_user_group FOREIGN KEY (group_id) REFERENCES back_group (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_product DROP CONSTRAINT FK_17DF9A76F6859C8C');
        $this->addSql('ALTER TABLE bl_quote_product DROP CONSTRAINT FK_17DF9A76B5B63A6B');
        $this->addSql('CREATE SEQUENCE bl_quote_product_id_seq');
        $this->addSql('SELECT setval(\'bl_quote_product_id_seq\', (SELECT MAX(id) FROM bl_quote_product))');
        $this->addSql('ALTER TABLE bl_quote_product ALTER id SET DEFAULT nextval(\'bl_quote_product_id_seq\')');
        $this->addSql('ALTER TABLE bl_quote_product ALTER unity_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_product ALTER vat_id SET NOT NULL');
        $this->addSql('ALTER TABLE bl_quote_product ALTER pdate TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote_product ALTER pdate DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_product ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote_product ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE bl_quote_product ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE bl_quote_product ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bl_quote_product ADD CONSTRAINT fk_bl_quote_product_unit FOREIGN KEY (unity_id) REFERENCES bl_unity (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bl_quote_product ADD CONSTRAINT fk_bl_quote_product_vat FOREIGN KEY (vat_id) REFERENCES bl_vat (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_17df9a76f8bd700d RENAME TO IDX_17DF9A76F6859C8C');
    }
}
