version: '2'
services:
    php:
        build: php-fpm
        restart: always 
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
    nginx:
        build: nginx
        restart: always 
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached

