controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

controllerscommon:    
    resource: ../../vendor/ssh/msjwtbundle/Controller/
    type: annotation
    