# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
    
nelmio_api_doc.swagger_ui:
    path: /api/doc/{area}/
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }